# ruff.toml
line-length = 88
target-version = "py38"

[lint]
select = ["E", "F", "B", "I"]

[format]
line-ending = "lf"
quote-style = "single"
skip-magic-trailing-comma = true
line-ending-newline = false
normalize-string-quotes = false